[2023-12-13T07:36:58.293+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v1.create_postgres_table scheduled__2022-12-15T00:00:00+00:00 [queued]>
[2023-12-13T07:36:58.308+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v1.create_postgres_table scheduled__2022-12-15T00:00:00+00:00 [queued]>
[2023-12-13T07:36:58.309+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-12-13T07:36:58.334+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-12-15 00:00:00+00:00
[2023-12-13T07:36:58.342+0000] {standard_task_runner.py:57} INFO - Started process 19023 to run task
[2023-12-13T07:36:58.345+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v1', 'create_postgres_table', 'scheduled__2022-12-15T00:00:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/dag_w_postgres_operator.py', '--cfg-path', '/tmp/tmpoejdq6if']
[2023-12-13T07:36:58.349+0000] {standard_task_runner.py:85} INFO - Job 111: Subtask create_postgres_table
[2023-12-13T07:36:58.396+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator_v1.create_postgres_table scheduled__2022-12-15T00:00:00+00:00 [running]> on host 6bd2d0daa4c2
[2023-12-13T07:36:58.467+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='vuhta' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v1' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2022-12-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-12-15T00:00:00+00:00'
[2023-12-13T07:36:58.467+0000] {sql.py:274} INFO - Executing: 
            create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-12-13T07:36:58.474+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-13T07:36:58.482+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-12-13T07:36:58.484+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.21.0.2), port 5432 failed: FATAL:  database "test" does not exist

[2023-12-13T07:36:58.492+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v1, task_id=create_postgres_table, execution_date=20221215T000000, start_date=20231213T073658, end_date=20231213T073658
[2023-12-13T07:36:58.502+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 111 for task create_postgres_table (connection to server at "postgres" (172.21.0.2), port 5432 failed: FATAL:  database "test" does not exist
; 19023)
[2023-12-13T07:36:58.516+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-13T07:36:58.530+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
